#include "keys.h"

#include <QMap>


static QMap<Qt::Key, QByteArray> keys = {
       {Qt::Key_Escape, "<Escape>"},
       {Qt::Key_Tab, "<Tab>"},
       {Qt::Key_Backtab, "<Backtab>"},
       {Qt::Key_Backspace, "<Backspace>"},
       {Qt::Key_Return, "<Return>"},
       {Qt::Key_Enter, "<Enter>"},
       {Qt::Key_Insert, "<Insert>"},
       {Qt::Key_Delete, "<Delete>"},
       {Qt::Key_Pause, "<Pause>"},
       {Qt::Key_Print, "<Print>"},
       {Qt::Key_SysReq, "<SysReq>"},
       {Qt::Key_Clear, "<Clear>"},
       {Qt::Key_Home, "<Home>"},
       {Qt::Key_End, "<End>"},
       {Qt::Key_Left, "<Left>"},
       {Qt::Key_Up, "<Up>"},
       {Qt::Key_Right, "<Right>"},
       {Qt::Key_Down, "<Down>"},
       {Qt::Key_PageUp, "<PageUp>"},
       {Qt::Key_PageDown, "<PageDown>"},
       {Qt::Key_Shift, "<Shift>"},
       {Qt::Key_Control, "<Control>"},
       {Qt::Key_Meta, "<Meta>"},
       {Qt::Key_Alt, "<Alt>"},
       {Qt::Key_CapsLock, "<CapsLock>"},
       {Qt::Key_NumLock, "<NumLock>"},
       {Qt::Key_ScrollLock, "<ScrollLock>"},
       {Qt::Key_F1, "<F1>"},
       {Qt::Key_F2, "<F2>"},
       {Qt::Key_F3, "<F3>"},
       {Qt::Key_F4, "<F4>"},
       {Qt::Key_F5, "<F5>"},
       {Qt::Key_F6, "<F6>"},
       {Qt::Key_F7, "<F7>"},
       {Qt::Key_F8, "<F8>"},
       {Qt::Key_F9, "<F9>"},
       {Qt::Key_F10, "<F10>"},
       {Qt::Key_F11, "<F11>"},
       {Qt::Key_F12, "<F12>"},
       {Qt::Key_F13, "<F13>"},
       {Qt::Key_F14, "<F14>"},
       {Qt::Key_F15, "<F15>"},
       {Qt::Key_F16, "<F16>"},
       {Qt::Key_F17, "<F17>"},
       {Qt::Key_F18, "<F18>"},
       {Qt::Key_F19, "<F19>"},
       {Qt::Key_F20, "<F20>"},
       {Qt::Key_F21, "<F21>"},
       {Qt::Key_F22, "<F22>"},
       {Qt::Key_F23, "<F23>"},
       {Qt::Key_F24, "<F24>"},
       {Qt::Key_F25, "<F25>"},
       {Qt::Key_F26, "<F26>"},
       {Qt::Key_F27, "<F27>"},
       {Qt::Key_F28, "<F28>"},
       {Qt::Key_F29, "<F29>"},
       {Qt::Key_F30, "<F30>"},
       {Qt::Key_F31, "<F31>"},
       {Qt::Key_F32, "<F32>"},
       {Qt::Key_F33, "<F33>"},
       {Qt::Key_F34, "<F34>"},
       {Qt::Key_F35, "<F35>"},
       {Qt::Key_Super_L, "<Super_L>"},
       {Qt::Key_Super_R, "<Super_R>"},
       {Qt::Key_Menu, "<Menu>"},
       {Qt::Key_Hyper_L, "<Hyper_L>"},
       {Qt::Key_Hyper_R, "<Hyper_R>"},
       {Qt::Key_Help, "<Help>"},
       {Qt::Key_Direction_L, "<Direction_L>"},
       {Qt::Key_Direction_R, "<Direction_R>"},
       {Qt::Key_Space, "<Space>"},
       {Qt::Key_Any, "<Any>"},
       {Qt::Key_Exclam, "<Exclam>"},
       {Qt::Key_QuoteDbl, "<QuoteDbl>"},
       {Qt::Key_NumberSign, "<NumberSign>"},
       {Qt::Key_Dollar, "$"},
       {Qt::Key_Percent, "%"},
       {Qt::Key_Ampersand, "<Ampersand>"},
       {Qt::Key_Apostrophe, "<Apostrophe>"},
       {Qt::Key_ParenLeft, "<ParenLeft>"},
       {Qt::Key_ParenRight, "<ParenRight>"},
       {Qt::Key_Asterisk, "<Asterisk>"},
       {Qt::Key_Plus, "+"},
       {Qt::Key_Comma, ","},
       {Qt::Key_Minus, "-"},
       {Qt::Key_Period, "*"},
       {Qt::Key_Slash, "/"},
       {Qt::Key_0, "0"},
       {Qt::Key_1, "1"},
       {Qt::Key_2, "2"},
       {Qt::Key_3, "3"},
       {Qt::Key_4, "4"},
       {Qt::Key_5, "5"},
       {Qt::Key_6, "6"},
       {Qt::Key_7, "7"},
       {Qt::Key_8, "8"},
       {Qt::Key_9, "9"},
       {Qt::Key_Colon, ":"},
       {Qt::Key_Semicolon, ";"},
       {Qt::Key_Less, "<Less>"},
       {Qt::Key_Equal, "="},
       {Qt::Key_Greater, "<Greater>"},
       {Qt::Key_Question, "?"},
       {Qt::Key_At, "<At>"},
       {Qt::Key_A, "A"},
       {Qt::Key_B, "B"},
       {Qt::Key_C, "C"},
       {Qt::Key_D, "D"},
       {Qt::Key_E, "E"},
       {Qt::Key_F, "F"},
       {Qt::Key_G, "G"},
       {Qt::Key_H, "H"},
       {Qt::Key_I, "I"},
       {Qt::Key_J, "J"},
       {Qt::Key_K, "K"},
       {Qt::Key_L, "L"},
       {Qt::Key_M, "M"},
       {Qt::Key_N, "N"},
       {Qt::Key_O, "O"},
       {Qt::Key_P, "P"},
       {Qt::Key_Q, "Q"},
       {Qt::Key_R, "R"},
       {Qt::Key_S, "S"},
       {Qt::Key_T, "T"},
       {Qt::Key_U, "U"},
       {Qt::Key_V, "V"},
       {Qt::Key_W, "W"},
       {Qt::Key_X, "X"},
       {Qt::Key_Y, "Y"},
       {Qt::Key_Z, "Z"},
       {Qt::Key_BracketLeft, "<BracketLeft>"},
       {Qt::Key_Backslash, "<Backslash>"},
       {Qt::Key_BracketRight, "<BracketRight>"},
       {Qt::Key_AsciiCircum, "<AsciiCircum>"},
       {Qt::Key_Underscore, "<Underscore>"},
       {Qt::Key_QuoteLeft, "<QuoteLeft>"},
       {Qt::Key_BraceLeft, "<BraceLeft>"},
       {Qt::Key_Bar, "<Bar>"},
       {Qt::Key_BraceRight, "<BraceRight>"},
       {Qt::Key_AsciiTilde, "<AsciiTilde>"},

{Qt::Key_nobreakspace, "<nobreakspace>"},
    {Qt::Key_exclamdown, "<exclamdown>"},
    {Qt::Key_cent, "<cent>"},
    {Qt::Key_sterling, "<sterling>"},
    {Qt::Key_currency, "<currency>"},
    {Qt::Key_yen, "<yen>"},
    {Qt::Key_brokenbar, "<brokenbar>"},
    {Qt::Key_section, "<section>"},
    {Qt::Key_diaeresis, "<diaeresis>"},
    {Qt::Key_copyright, "<copyright>"},
    {Qt::Key_ordfeminine, "<ordfeminine>"},
    {Qt::Key_guillemotleft, "<guillemotleft>"},
    {Qt::Key_notsign, "<notsign>"},
    {Qt::Key_hyphen, "<hyphen>"},
    {Qt::Key_registered, "<registered>"},
    {Qt::Key_macron, "<macron>"},
    {Qt::Key_degree, "<degree>"},
    {Qt::Key_plusminus, "<plusminus>"},
    {Qt::Key_twosuperior, "<twosuperior>"},
    {Qt::Key_threesuperior, "<threesuperior>"},
    {Qt::Key_acute, "<acute>"},
    {Qt::Key_mu, "<mu>"},
    {Qt::Key_paragraph, "<paragraph>"},
    {Qt::Key_periodcentered, "<periodcentered>"},
    {Qt::Key_cedilla, "<cedilla>"},
    {Qt::Key_onesuperior, "<onesuperior>"},
    {Qt::Key_masculine, "<masculine>"},
    {Qt::Key_guillemotright, "<guillemotright>"},
    {Qt::Key_onequarter, "<onequarter>"},
    {Qt::Key_onehalf, "<onehalf>"},
    {Qt::Key_threequarters, "<threequarters>"},
    {Qt::Key_questiondown, "<questiondown>"},
    {Qt::Key_Agrave, "<Agrave>"},
    {Qt::Key_Aacute, "<Aacute>"},
    {Qt::Key_Acircumflex, "<Acircumflex>"},
    {Qt::Key_Atilde, "<Atilde>"},
    {Qt::Key_Adiaeresis, "<Adiaeresis>"},
    {Qt::Key_Aring, "<Aring>"},
    {Qt::Key_AE, "<AE>"},
    {Qt::Key_Ccedilla, "<Ccedilla>"},
    {Qt::Key_Egrave, "<Egrave>"},
    {Qt::Key_Eacute, "<Eacute>"},
    {Qt::Key_Ecircumflex, "<Ecircumflex>"},
    {Qt::Key_Ediaeresis, "<Ediaeresis>"},
    {Qt::Key_Igrave, "<Igrave>"},
    {Qt::Key_Iacute, "<Iacute>"},
    {Qt::Key_Icircumflex, "<Icircumflex>"},
    {Qt::Key_Idiaeresis, "<Idiaeresis>"},
    {Qt::Key_ETH, "<ETH>"},
    {Qt::Key_Ntilde, "<Ntilde>"},
    {Qt::Key_Ograve, "<Ograve>"},
    {Qt::Key_Oacute, "<Oacute>"},
    {Qt::Key_Ocircumflex, "<Ocircumflex>"},
    {Qt::Key_Otilde, "<Otilde>"},
    {Qt::Key_Odiaeresis, "<Odiaeresis>"},
    {Qt::Key_multiply, "<multiply>"},
    {Qt::Key_Ooblique, "<Ooblique>"},
    {Qt::Key_Ugrave, "<Ugrave>"},
    {Qt::Key_Uacute, "<Uacute>"},
    {Qt::Key_Ucircumflex, "<Ucircumflex>"},
    {Qt::Key_Udiaeresis, "<Udiaeresis>"},
    {Qt::Key_Yacute, "<Yacute>"},
    {Qt::Key_THORN, "<THORN>"},
    {Qt::Key_ssharp, "<ssharp>"},
    {Qt::Key_division, "<division>"},
    {Qt::Key_ydiaeresis, "<ydiaeresis>"},

    // International input method support (X keycode - 0xEE00, the
    // definition follows Qt/Embedded 2.3.7) Only interesting if
    // you are writing your own input method

    // International & multi-key character composition
    {Qt::Key_AltGr, "<AltGr>"},
    {Qt::Key_Multi_key, "<Multi_key>"},
    {Qt::Key_Codeinput, "<Codeinput>"},
    {Qt::Key_SingleCandidate, "<SingleCandidate>"},
    {Qt::Key_MultipleCandidate, "<MultipleCandidate>"},
    {Qt::Key_PreviousCandidate, "<PreviousCandidate>"},

    // Misc Functions
    {Qt::Key_Mode_switch, "<Mode_switch>"},
    //Key_script_switch       = 0x0100117e,  // Alias for mode_switch

    // Japanese keyboard support
    {Qt::Key_Kanji, "<Kanji>"},
    {Qt::Key_Muhenkan, "<Muhenkan>"},
    //Key_Henkan_Mode         = 0x01001123,  // Start/Stop Conversion
    {Qt::Key_Henkan, "<Henkan>"},
    {Qt::Key_Romaji, "<Romaji>"},
    {Qt::Key_Hiragana, "<Hiragana>"},
    {Qt::Key_Katakana, "<Katakana>"},
    {Qt::Key_Hiragana_Katakana, "<Hiragana_Katakana>"},
    {Qt::Key_Zenkaku, "<Zenkaku>"},
    {Qt::Key_Hankaku, "<Hankaku>"},
    {Qt::Key_Zenkaku_Hankaku, "<Zenkaku_Hankaku>"},
    {Qt::Key_Touroku, "<Touroku>"},
    {Qt::Key_Massyo, "<Massyo>"},
    {Qt::Key_Kana_Lock, "<Kana_Lock>"},
    {Qt::Key_Kana_Shift, "<Kana_Shift>"},
    {Qt::Key_Eisu_Shift, "<Eisu_Shift>"},
    {Qt::Key_Eisu_toggle, "<Eisu_toggle>"},
    //Key_Kanji_Bangou        = 0x01001137,  // Codeinput
    //Key_Zen_Koho            = 0x0100113d,  // Multiple/All Candidate(s)
    //Key_Mae_Koho            = 0x0100113e,  // Previous Candidate

    // Korean keyboard support
    //
    // In fact, many Korean users need only 2 keys, Key_Hangul and
    // Key_Hangul_Hanja. But rest of the keys are good for future.

    {Qt::Key_Hangul, "<Hangul>"},
    {Qt::Key_Hangul_Start, "<Hangul_Start>"},
    {Qt::Key_Hangul_End, "<Hangul_End>"},
    {Qt::Key_Hangul_Hanja, "<Hangul_Hanja>"},
    {Qt::Key_Hangul_Jamo, "<Hangul_Jamo>"},
    {Qt::Key_Hangul_Romaja, "<Hangul_Romaja>"},
    //Key_Hangul_Codeinput    = 0x01001137,  // Hangul code input mode
    {Qt::Key_Hangul_Jeonja, "<Hangul_Jeonja>"},
    {Qt::Key_Hangul_Banja, "<Hangul_Banja>"},
    {Qt::Key_Hangul_PreHanja, "<Hangul_PreHanja>"},
    {Qt::Key_Hangul_PostHanja, "<Hangul_PostHanja>"},
    //Key_Hangul_SingleCandidate   = 0x0100113c,  // Single candidate
    //Key_Hangul_MultipleCandidate = 0x0100113d,  // Multiple candidate
    //Key_Hangul_PreviousCandidate = 0x0100113e,  // Previous candidate
    {Qt::Key_Hangul_Special, "<Hangul_Special>"},
    //Key_Hangul_switch       = 0x0100117e,  // Alias for mode_switch

    // dead keys (X keycode - 0xED00 to avoid the conflict)
    {Qt::Key_Dead_Grave, "<Dead_Grave>"},
    {Qt::Key_Dead_Acute, "<Dead_Acute>"},
    {Qt::Key_Dead_Circumflex, "<Dead_Circumflex>"},
    {Qt::Key_Dead_Tilde, "<Dead_Tilde>"},
    {Qt::Key_Dead_Macron, "<Dead_Macron>"},
    {Qt::Key_Dead_Breve, "<Dead_Breve>"},
    {Qt::Key_Dead_Abovedot, "<Dead_Abovedot>"},
    {Qt::Key_Dead_Diaeresis, "<Dead_Diaeresis>"},
    {Qt::Key_Dead_Abovering, "<Dead_Abovering>"},
    {Qt::Key_Dead_Doubleacute, "<Dead_Doubleacute>"},
    {Qt::Key_Dead_Caron, "<Dead_Caron>"},
    {Qt::Key_Dead_Cedilla, "<Dead_Cedilla>"},
    {Qt::Key_Dead_Ogonek, "<Dead_Ogonek>"},
    {Qt::Key_Dead_Iota, "<Dead_Iota>"},
    {Qt::Key_Dead_Voiced_Sound, "<Dead_Voiced_Sound>"},
    {Qt::Key_Dead_Semivoiced_Sound, "<Dead_Semivoiced_Sound>"},
    {Qt::Key_Dead_Belowdot, "<Dead_Belowdot>"},
    {Qt::Key_Dead_Hook, "<Dead_Hook>"},
    {Qt::Key_Dead_Horn, "<Dead_Horn>"},
#if QT_VERSION > QT_VERSION_CHECK(5, 10, 0)
    {Qt::Key_Dead_Stroke, "<Dead_Stroke>"},
    {Qt::Key_Dead_Abovecomma, "<Dead_Abovecomma>"},
    {Qt::Key_Dead_Abovereversedcomma, "<Dead_Abovereversedcomma>"},
    {Qt::Key_Dead_Doublegrave, "<Dead_Doublegrave>"},
    {Qt::Key_Dead_Belowring, "<Dead_Belowring>"},
    {Qt::Key_Dead_Belowmacron, "<Dead_Belowmacron>"},
    {Qt::Key_Dead_Belowcircumflex, "<Dead_Belowcircumflex>"},
    {Qt::Key_Dead_Belowtilde, "<Dead_Belowtilde>"},
    {Qt::Key_Dead_Belowbreve, "<Dead_Belowbreve>"},
    {Qt::Key_Dead_Belowdiaeresis, "<Dead_Belowdiaeresis>"},
    {Qt::Key_Dead_Invertedbreve, "<Dead_Invertedbreve>"},
    {Qt::Key_Dead_Belowcomma, "<Dead_Belowcomma>"},
    {Qt::Key_Dead_Currency, "<Dead_Currency>"},
    {Qt::Key_Dead_a, "<Dead_a>"},
    {Qt::Key_Dead_A, "<Dead_A>"},
    {Qt::Key_Dead_e, "<Dead_e>"},
    {Qt::Key_Dead_E, "<Dead_E>"},
    {Qt::Key_Dead_i, "<Dead_i>"},
    {Qt::Key_Dead_I, "<Dead_I>"},
    {Qt::Key_Dead_o, "<Dead_o>"},
    {Qt::Key_Dead_O, "<Dead_O>"},
    {Qt::Key_Dead_u, "<Dead_u>"},
    {Qt::Key_Dead_U, "<Dead_U>"},
    {Qt::Key_Dead_Small_Schwa, "<Dead_Small_Schwa>"},
    {Qt::Key_Dead_Capital_Schwa, "<Dead_Capital_Schwa>"},
    {Qt::Key_Dead_Greek, "<Dead_Greek>"},
    {Qt::Key_Dead_Lowline, "<Dead_Lowline>"},
    {Qt::Key_Dead_Aboveverticalline, "<Dead_Aboveverticalline>"},
    {Qt::Key_Dead_Belowverticalline, "<Dead_Belowverticalline>"},
    {Qt::Key_Dead_Longsolidusoverlay, "<Dead_Longsolidusoverlay>"},
#endif
    // multimedia/internet keys - ignored by default - see QKeyEvent c'tor
    {Qt::Key_Back, "<Back>"},
    {Qt::Key_Forward, "<Forward>"},
    {Qt::Key_Stop, "<Stop>"},
    {Qt::Key_Refresh, "<Refresh>"},
    {Qt::Key_VolumeDown, "<VolumeDown>"},
    {Qt::Key_VolumeMute, "<VolumeMute>"},
    {Qt::Key_VolumeUp, "<VolumeUp>"},
    {Qt::Key_BassBoost, "<BassBoost>"},
    {Qt::Key_BassUp, "<BassUp>"},
    {Qt::Key_BassDown, "<BassDown>"},
    {Qt::Key_TrebleUp, "<TrebleUp>"},
    {Qt::Key_TrebleDown, "<TrebleDown>"},
    {Qt::Key_MediaPlay, "<MediaPlay>"},
    {Qt::Key_MediaStop, "<MediaStop>"},
    {Qt::Key_MediaPrevious, "<MediaPrevious>"},
    {Qt::Key_MediaNext, "<MediaNext>"},
    {Qt::Key_MediaRecord, "<MediaRecord>"},
    {Qt::Key_MediaPause, "<MediaPause>"},
    {Qt::Key_MediaTogglePlayPause, "<MediaTogglePlayPause>"},
    {Qt::Key_HomePage, "<HomePage>"},
    {Qt::Key_Favorites, "<Favorites>"},
    {Qt::Key_Search, "<Search>"},
    {Qt::Key_Standby, "<Standby>"},
    {Qt::Key_OpenUrl, "<OpenUrl>"},
    {Qt::Key_LaunchMail, "<LaunchMail>"},
    {Qt::Key_LaunchMedia, "<LaunchMedia>"},
    {Qt::Key_Launch0, "<Launch0>"},
    {Qt::Key_Launch1, "<Launch1>"},
    {Qt::Key_Launch2, "<Launch2>"},
    {Qt::Key_Launch3, "<Launch3>"},
    {Qt::Key_Launch4, "<Launch4>"},
    {Qt::Key_Launch5, "<Launch5>"},
    {Qt::Key_Launch6, "<Launch6>"},
    {Qt::Key_Launch7, "<Launch7>"},
    {Qt::Key_Launch8, "<Launch8>"},
    {Qt::Key_Launch9, "<Launch9>"},
    {Qt::Key_LaunchA, "<LaunchA>"},
    {Qt::Key_LaunchB, "<LaunchB>"},
    {Qt::Key_LaunchC, "<LaunchC>"},
    {Qt::Key_LaunchD, "<LaunchD>"},
    {Qt::Key_LaunchE, "<LaunchE>"},
    {Qt::Key_LaunchF, "<LaunchF>"},
    {Qt::Key_MonBrightnessUp, "<MonBrightnessUp>"},
    {Qt::Key_MonBrightnessDown, "<MonBrightnessDown>"},
    {Qt::Key_KeyboardLightOnOff, "<KeyboardLightOnOff>"},
    {Qt::Key_KeyboardBrightnessUp, "<KeyboardBrightnessUp>"},
    {Qt::Key_KeyboardBrightnessDown, "<KeyboardBrightnessDown>"},
    {Qt::Key_PowerOff, "<PowerOff>"},
    {Qt::Key_WakeUp, "<WakeUp>"},
    {Qt::Key_Eject, "<Eject>"},
    {Qt::Key_ScreenSaver, "<ScreenSaver>"},
    {Qt::Key_WWW, "<WWW>"},
    {Qt::Key_Memo, "<Memo>"},
    {Qt::Key_LightBulb, "<LightBulb>"},
    {Qt::Key_Shop, "<Shop>"},
    {Qt::Key_History, "<History>"},
    {Qt::Key_AddFavorite, "<AddFavorite>"},
    {Qt::Key_HotLinks, "<HotLinks>"},
    {Qt::Key_BrightnessAdjust, "<BrightnessAdjust>"},
    {Qt::Key_Finance, "<Finance>"},
    {Qt::Key_Community, "<Community>"},
    {Qt::Key_AudioRewind, "<AudioRewind>"},
    {Qt::Key_BackForward, "<BackForward>"},
    {Qt::Key_ApplicationLeft, "<ApplicationLeft>"},
    {Qt::Key_ApplicationRight, "<ApplicationRight>"},
    {Qt::Key_Book, "<Book>"},
    {Qt::Key_CD, "<CD>"},
    {Qt::Key_Calculator, "<Calculator>"},
    {Qt::Key_ToDoList, "<ToDoList>"},
    {Qt::Key_ClearGrab, "<ClearGrab>"},
    {Qt::Key_Close, "<Close>"},
    {Qt::Key_Copy, "<Copy>"},
    {Qt::Key_Cut, "<Cut>"},
    {Qt::Key_Display, "<Display>"},
    {Qt::Key_DOS, "<DOS>"},
    {Qt::Key_Documents, "<Documents>"},
    {Qt::Key_Excel, "<Excel>"},
    {Qt::Key_Explorer, "<Explorer>"},
    {Qt::Key_Game, "<Game>"},
    {Qt::Key_Go, "<Go>"},
    {Qt::Key_iTouch, "<iTouch>"},
    {Qt::Key_LogOff, "<LogOff>"},
    {Qt::Key_Market, "<Market>"},
    {Qt::Key_Meeting, "<Meeting>"},
    {Qt::Key_MenuKB, "<MenuKB>"},
    {Qt::Key_MenuPB, "<MenuPB>"},
    {Qt::Key_MySites, "<MySites>"},
    {Qt::Key_News, "<News>"},
    {Qt::Key_OfficeHome, "<OfficeHome>"},
    {Qt::Key_Option, "<Option>"},
    {Qt::Key_Paste, "<Paste>"},
    {Qt::Key_Phone, "<Phone>"},
    {Qt::Key_Calendar, "<Calendar>"},
    {Qt::Key_Reply, "<Reply>"},
    {Qt::Key_Reload, "<Reload>"},
    {Qt::Key_RotateWindows, "<RotateWindows>"},
    {Qt::Key_RotationPB, "<RotationPB>"},
    {Qt::Key_RotationKB, "<RotationKB>"},
    {Qt::Key_Save, "<Save>"},
    {Qt::Key_Send, "<Send>"},
    {Qt::Key_Spell, "<Spell>"},
    {Qt::Key_SplitScreen, "<SplitScreen>"},
    {Qt::Key_Support, "<Support>"},
    {Qt::Key_TaskPane, "<TaskPane>"},
    {Qt::Key_Terminal, "<Terminal>"},
    {Qt::Key_Tools, "<Tools>"},
    {Qt::Key_Travel, "<Travel>"},
    {Qt::Key_Video, "<Video>"},
    {Qt::Key_Word, "<Word>"},
    {Qt::Key_Xfer, "<Xfer>"},
    {Qt::Key_ZoomIn, "<ZoomIn>"},
    {Qt::Key_ZoomOut, "<ZoomOut>"},
    {Qt::Key_Away, "<Away>"},
    {Qt::Key_Messenger, "<Messenger>"},
    {Qt::Key_WebCam, "<WebCam>"},
    {Qt::Key_MailForward, "<MailForward>"},
    {Qt::Key_Pictures, "<Pictures>"},
    {Qt::Key_Music, "<Music>"},
    {Qt::Key_Battery, "<Battery>"},
    {Qt::Key_Bluetooth, "<Bluetooth>"},
    {Qt::Key_WLAN, "<WLAN>"},
    {Qt::Key_UWB, "<UWB>"},
    {Qt::Key_AudioForward, "<AudioForward>"},
    {Qt::Key_AudioRepeat, "<AudioRepeat>"},
    {Qt::Key_AudioRandomPlay, "<AudioRandomPlay>"},
    {Qt::Key_Subtitle, "<Subtitle>"},
    {Qt::Key_AudioCycleTrack, "<AudioCycleTrack>"},
    {Qt::Key_Time, "<Time>"},
    {Qt::Key_Hibernate, "<Hibernate>"},
    {Qt::Key_View, "<View>"},
    {Qt::Key_TopMenu, "<TopMenu>"},
    {Qt::Key_PowerDown, "<PowerDown>"},
    {Qt::Key_Suspend, "<Suspend>"},
    {Qt::Key_ContrastAdjust, "<ContrastAdjust>"},

    {Qt::Key_LaunchG, "<LaunchG>"},
    {Qt::Key_LaunchH, "<LaunchH>"},

    {Qt::Key_TouchpadToggle, "<TouchpadToggle>"},
    {Qt::Key_TouchpadOn, "<TouchpadOn>"},
    {Qt::Key_TouchpadOff, "<TouchpadOff>"},

    {Qt::Key_MicMute, "<MicMute>"},

    {Qt::Key_Red, "<Red>"},
    {Qt::Key_Green, "<Green>"},
    {Qt::Key_Yellow, "<Yellow>"},
    {Qt::Key_Blue, "<Blue>"},

    {Qt::Key_ChannelUp, "<ChannelUp>"},
    {Qt::Key_ChannelDown, "<ChannelDown>"},

    {Qt::Key_Guide, "<Guide>"},
    {Qt::Key_Info, "<Info>"},
    {Qt::Key_Settings, "<Settings>"},

    {Qt::Key_MicVolumeUp, "<MicVolumeUp>"},
    {Qt::Key_MicVolumeDown, "<MicVolumeDown>"},

    {Qt::Key_New, "<New>"},
    {Qt::Key_Open, "<Open>"},
    {Qt::Key_Find, "<Find>"},
    {Qt::Key_Undo, "<Undo>"},
    {Qt::Key_Redo, "<Redo>"},

    {Qt::Key_MediaLast, "<MediaLast>"},

    // Keypad navigation keys
    {Qt::Key_Select, "<Select>"},
    {Qt::Key_Yes, "<Yes>"},
    {Qt::Key_No, "<No>"},

    // Newer misc keys
    {Qt::Key_Cancel, "<Cancel>"},
    {Qt::Key_Printer, "<Printer>"},
    {Qt::Key_Execute, "<Execute>"},
    {Qt::Key_Sleep, "<Sleep>"},
    {Qt::Key_Play, "<Play>"},
    {Qt::Key_Zoom, "<Zoom>"},
    //Key_Jisho   = 0x01020007, // IME: Dictionary key
    //Key_Oyayubi_Left = 0x01020008, // IME: Left Oyayubi key
    //Key_Oyayubi_Right = 0x01020009, // IME: Right Oyayubi key
    {Qt::Key_Exit, "<Exit>"},

    // Device keys
    {Qt::Key_Context1, "<Context1>"},
    {Qt::Key_Context2, "<Context2>"},
    {Qt::Key_Context3, "<Context3>"},
    {Qt::Key_Context4, "<Context4>"},
    {Qt::Key_Call, "<Call>"},
    {Qt::Key_Hangup, "<Hangup>"},
    {Qt::Key_Flip, "<Flip>"},
    {Qt::Key_ToggleCallHangup, "<ToggleCallHangup>"},
    {Qt::Key_VoiceDial, "<VoiceDial>"},
    {Qt::Key_LastNumberRedial, "<LastNumberRedial>"},

    {Qt::Key_Camera, "<Camera>"},
    {Qt::Key_CameraFocus, "<CameraFocus>"},

{Qt::Key_unknown, "unknown"}
};

#ifdef RAT_OS_LINUX
#include <QTextStream>
#   include "x11keys.h"
#   include <X11/Xlib.h>
#   include <X11/Xutil.h>

    static QMap<Qt::Key, KeySym> x11keys = {
        // misc keys
        {Qt::Key_0, XK_0},
        {Qt::Key_1, XK_1},
        {Qt::Key_2, XK_2},
        {Qt::Key_3, XK_3},
        {Qt::Key_4, XK_4},
        {Qt::Key_5, XK_5},
        {Qt::Key_6, XK_6},
        {Qt::Key_7, XK_7},
        {Qt::Key_8, XK_8},
        {Qt::Key_9, XK_9},

        {Qt::Key_A, XK_A},
        {Qt::Key_B, XK_B},
        {Qt::Key_C, XK_C},
        {Qt::Key_D, XK_D},
        {Qt::Key_E, XK_E},
        {Qt::Key_F, XK_F},
        {Qt::Key_G, XK_G},
        {Qt::Key_H, XK_H},
        {Qt::Key_I, XK_I},
        {Qt::Key_J, XK_J},
        {Qt::Key_K, XK_K},
        {Qt::Key_L, XK_L},
        {Qt::Key_M, XK_M},
        {Qt::Key_N, XK_N},
        {Qt::Key_O, XK_O},
        {Qt::Key_P, XK_P},
        {Qt::Key_Q, XK_Q},
        {Qt::Key_R, XK_R},
        {Qt::Key_S, XK_S},
        {Qt::Key_T, XK_T},
        {Qt::Key_U, XK_U},
        {Qt::Key_V, XK_V},
        {Qt::Key_W, XK_W},
        {Qt::Key_X, XK_X},
        {Qt::Key_Y, XK_Y},
        {Qt::Key_Z, XK_Z},

        {Qt::Key_A, XK_a},
        {Qt::Key_B, XK_b},
        {Qt::Key_C, XK_c},
        {Qt::Key_D, XK_d},
        {Qt::Key_E, XK_e},
        {Qt::Key_F, XK_f},
        {Qt::Key_G, XK_g},
        {Qt::Key_H, XK_h},
        {Qt::Key_I, XK_i},
        {Qt::Key_J, XK_j},
        {Qt::Key_K, XK_k},
        {Qt::Key_L, XK_l},
        {Qt::Key_M, XK_m},
        {Qt::Key_N, XK_n},
        {Qt::Key_O, XK_o},
        {Qt::Key_P, XK_p},
        {Qt::Key_Q, XK_q},
        {Qt::Key_R, XK_r},
        {Qt::Key_S, XK_s},
        {Qt::Key_T, XK_t},
        {Qt::Key_U, XK_u},
        {Qt::Key_V, XK_v},
        {Qt::Key_W, XK_w},
        {Qt::Key_X, XK_x},
        {Qt::Key_Y, XK_y},
        {Qt::Key_Z, XK_z},

        {Qt::Key_F1, XK_F1},
        {Qt::Key_F2, XK_F2},
        {Qt::Key_F3, XK_F3},
        {Qt::Key_F4, XK_F4},
        {Qt::Key_F5, XK_F5},
        {Qt::Key_F6, XK_F6},
        {Qt::Key_F7, XK_F7},
        {Qt::Key_F8, XK_F8},
        {Qt::Key_F9, XK_F9},
        {Qt::Key_F10, XK_F10},
        {Qt::Key_F11, XK_F11},
        {Qt::Key_F13, XK_F13},
        {Qt::Key_F14, XK_F14},
        {Qt::Key_F15, XK_F15},
        {Qt::Key_F16, XK_F16},
        {Qt::Key_F17, XK_F17},
        {Qt::Key_F18, XK_F18},
        {Qt::Key_F19, XK_F19},
        {Qt::Key_F20, XK_F20},
        {Qt::Key_F21, XK_F21},
        {Qt::Key_F22, XK_F22},
        {Qt::Key_F23, XK_F23},
        {Qt::Key_F24, XK_F24},
        {Qt::Key_F25, XK_F25},
        {Qt::Key_F26, XK_F26},
        {Qt::Key_F27, XK_F27},
        {Qt::Key_F28, XK_F28},
        {Qt::Key_F29, XK_F29},
        {Qt::Key_F30, XK_F30},
        {Qt::Key_F31, XK_F31},
        {Qt::Key_F32, XK_F32},
        {Qt::Key_F33, XK_F33},
        {Qt::Key_F34, XK_F34},
        {Qt::Key_F35, XK_F35},

        {Qt::Key_Escape, XK_Escape},
        {Qt::Key_Tab, XK_Tab},
        {Qt::Key_Backtab, XK_ISO_Left_Tab},
        {Qt::Key_Backspace, XK_BackSpace},
        {Qt::Key_Return, XK_Return},
        {Qt::Key_Insert, XK_Insert},
        {Qt::Key_Delete, XK_Delete},
        {Qt::Key_Delete, XK_Clear},
        {Qt::Key_Pause, XK_Pause},
        {Qt::Key_Print, XK_Print},
        {Qt::Key_SysReq, 0x1005FF60},
        {Qt::Key_SysReq, 0x1007ff00},

        // cursor movement

        {Qt::Key_Home, XK_Home},
        {Qt::Key_End, XK_End},
        {Qt::Key_Left, XK_Left},
        {Qt::Key_Up, XK_Up},
        {Qt::Key_Right, XK_Right},
        {Qt::Key_Down, XK_Down},
        {Qt::Key_PageUp, XK_Prior},
        {Qt::Key_PageDown, XK_Next},

        // modifiers

        {Qt::Key_Shift, XK_Shift_L},
        {Qt::Key_Shift, XK_Shift_R},
        {Qt::Key_Shift, XK_Shift_Lock},
        {Qt::Key_Control, XK_Control_L},
        {Qt::Key_Control, XK_Control_R},
        {Qt::Key_Meta, XK_Meta_L},
        {Qt::Key_Meta, XK_Meta_R},
        {Qt::Key_Alt, XK_Alt_L},
        {Qt::Key_Alt, XK_Alt_R},
        {Qt::Key_CapsLock, XK_Caps_Lock},
        {Qt::Key_NumLock, XK_Num_Lock},
        {Qt::Key_ScrollLock, XK_Scroll_Lock},
        {Qt::Key_Super_L, XK_Super_L},
        {Qt::Key_Super_R, XK_Super_R},
        {Qt::Key_Menu, XK_Menu},
        {Qt::Key_Hyper_L, XK_Hyper_L},
        {Qt::Key_Hyper_R, XK_Hyper_R},
        {Qt::Key_Help, XK_Help},
        {Qt::Key_Backtab, 0x1000FF74},
        {Qt::Key_F11, 0x1005FF10},
        {Qt::Key_F12, 0x1005FF11},

        // numeric and function keypad keys

        {Qt::Key_Space, XK_KP_Space},
        {Qt::Key_Tab, XK_KP_Tab},
        {Qt::Key_Enter, XK_KP_Enter},
        //{Qt::Key_F1, //XK_KP_F1},
        //{Qt::Key_F2, //XK_KP_F2},
        //{Qt::Key_F3, //XK_KP_F3},
        //{Qt::Key_F4, //XK_KP_F4},
        {Qt::Key_Home, XK_KP_Home},
        {Qt::Key_Left, XK_KP_Left},
        {Qt::Key_Up, XK_KP_Up},
        {Qt::Key_Right, XK_KP_Right},
        {Qt::Key_Down, XK_KP_Down},
        {Qt::Key_PageUp, XK_KP_Prior},
        {Qt::Key_PageDown, XK_KP_Next},
        {Qt::Key_End, XK_KP_End},
        {Qt::Key_Clear, XK_KP_Begin},
        {Qt::Key_Insert, XK_KP_Insert},
        {Qt::Key_Delete, XK_KP_Delete},
        {Qt::Key_Equal, XK_KP_Equal},
        {Qt::Key_Asterisk, XK_KP_Multiply},
        {Qt::Key_Plus, XK_KP_Add},
        {Qt::Key_Comma, XK_KP_Separator},
        {Qt::Key_Minus, XK_KP_Subtract},
        {Qt::Key_Period, XK_KP_Decimal},
        {Qt::Key_Slash, XK_KP_Divide},

        // International input method support keys

        // International & multi-key character composition
        {Qt::Key_AltGr, XK_ISO_Level3_Shift},
        {Qt::Key_Multi_key, XK_Multi_key},
        {Qt::Key_Codeinput, XK_Codeinput},
        {Qt::Key_SingleCandidate, XK_SingleCandidate},
        {Qt::Key_MultipleCandidate, XK_MultipleCandidate},
        {Qt::Key_PreviousCandidate, XK_PreviousCandidate},

        // Misc Functions
        {Qt::Key_Mode_switch, XK_Mode_switch},
        {Qt::Key_Mode_switch, XK_script_switch},

        // Japanese keyboard support
        {Qt::Key_Kanji, XK_Kanji},
        {Qt::Key_Muhenkan, XK_Muhenkan},
        //{Qt::Key_Henkan_Mode, //XK_Henkan_Mode},
        {Qt::Key_Henkan, XK_Henkan_Mode},
        {Qt::Key_Henkan, XK_Henkan},
        {Qt::Key_Romaji, XK_Romaji},
        {Qt::Key_Hiragana, XK_Hiragana},
        {Qt::Key_Katakana, XK_Katakana},
        {Qt::Key_Hiragana_Katakana, XK_Hiragana_Katakana},
        {Qt::Key_Zenkaku, XK_Zenkaku},
        {Qt::Key_Hankaku, XK_Hankaku},
        {Qt::Key_Zenkaku_Hankaku, XK_Zenkaku_Hankaku},
        {Qt::Key_Touroku, XK_Touroku},
        {Qt::Key_Massyo, XK_Massyo},
        {Qt::Key_Kana_Lock, XK_Kana_Lock},
        {Qt::Key_Kana_Shift, XK_Kana_Shift},
        {Qt::Key_Eisu_Shift, XK_Eisu_Shift},
        {Qt::Key_Eisu_toggle, XK_Eisu_toggle},
        //{Qt::Key_Kanji_Bangou, //XK_Kanji_Bangou},
        //{Qt::Key_Zen_Koho, //XK_Zen_Koho},
        //{Qt::Key_Mae_Koho, //XK_Mae_Koho},
        {Qt::Key_Codeinput, XK_Kanji_Bangou},
        {Qt::Key_MultipleCandidate, XK_Zen_Koho},
        {Qt::Key_PreviousCandidate, XK_Mae_Koho},

        // dead keys
        {Qt::Key_Dead_Grave, XK_dead_grave},
        {Qt::Key_Dead_Acute, XK_dead_acute},
        {Qt::Key_Dead_Circumflex, XK_dead_circumflex},
        {Qt::Key_Dead_Tilde, XK_dead_tilde},
        {Qt::Key_Dead_Macron, XK_dead_macron},
        {Qt::Key_Dead_Breve, XK_dead_breve},
        {Qt::Key_Dead_Abovedot, XK_dead_abovedot},
        {Qt::Key_Dead_Diaeresis, XK_dead_diaeresis},
        {Qt::Key_Dead_Abovering, XK_dead_abovering},
        {Qt::Key_Dead_Doubleacute, XK_dead_doubleacute},
        {Qt::Key_Dead_Caron, XK_dead_caron},
        {Qt::Key_Dead_Cedilla, XK_dead_cedilla},
        {Qt::Key_Dead_Ogonek, XK_dead_ogonek},
        {Qt::Key_Dead_Iota, XK_dead_iota},
        {Qt::Key_Dead_Voiced_Sound, XK_dead_voiced_sound},
        {Qt::Key_Dead_Semivoiced_Sound, XK_dead_semivoiced_sound},
        {Qt::Key_Dead_Belowdot, XK_dead_belowdot},
        {Qt::Key_Dead_Hook, XK_dead_hook},
        {Qt::Key_Dead_Horn, XK_dead_horn},

        // Special keys from X.org - This include multimedia keys,
        // wireless/bluetooth/uwb keys, special launcher keys, etc.
        {Qt::Key_Back, XF86XK_Back},
        {Qt::Key_Forward, XF86XK_Forward},
        {Qt::Key_Stop, XF86XK_Stop},
        {Qt::Key_Refresh, XF86XK_Refresh},
        {Qt::Key_Favorites, XF86XK_Favorites},
        {Qt::Key_LaunchMedia, XF86XK_AudioMedia},
        {Qt::Key_OpenUrl, XF86XK_OpenURL},
        {Qt::Key_HomePage, XF86XK_HomePage},
        {Qt::Key_Search, XF86XK_Search},
        {Qt::Key_VolumeDown, XF86XK_AudioLowerVolume},
        {Qt::Key_VolumeMute, XF86XK_AudioMute},
        {Qt::Key_VolumeUp, XF86XK_AudioRaiseVolume},
        {Qt::Key_MediaPlay, XF86XK_AudioPlay},
        {Qt::Key_MediaStop, XF86XK_AudioStop},
        {Qt::Key_MediaPrevious, XF86XK_AudioPrev},
        {Qt::Key_MediaNext, XF86XK_AudioNext},
        {Qt::Key_MediaRecord, XF86XK_AudioRecord},
        {Qt::Key_MediaPause, XF86XK_AudioPause},
        {Qt::Key_LaunchMail, XF86XK_Mail},
        {Qt::Key_Launch0, XF86XK_MyComputer},
        {Qt::Key_Launch1, XF86XK_Calculator},
        {Qt::Key_Memo, XF86XK_Memo},
        {Qt::Key_ToDoList, XF86XK_ToDoList},
        {Qt::Key_Calendar, XF86XK_Calendar},
        {Qt::Key_PowerDown, XF86XK_PowerDown},
        {Qt::Key_ContrastAdjust, XF86XK_ContrastAdjust},
        {Qt::Key_Standby, XF86XK_Standby},
        {Qt::Key_MonBrightnessUp, XF86XK_MonBrightnessUp},
        {Qt::Key_MonBrightnessDown, XF86XK_MonBrightnessDown},
        {Qt::Key_KeyboardLightOnOff, XF86XK_KbdLightOnOff},
        {Qt::Key_KeyboardBrightnessUp, XF86XK_KbdBrightnessUp},
        {Qt::Key_KeyboardBrightnessDown, XF86XK_KbdBrightnessDown},
        {Qt::Key_PowerOff, XF86XK_PowerOff},
        {Qt::Key_WakeUp, XF86XK_WakeUp},
        {Qt::Key_Eject, XF86XK_Eject},
        {Qt::Key_ScreenSaver, XF86XK_ScreenSaver},
        {Qt::Key_WWW, XF86XK_WWW},
        {Qt::Key_Sleep, XF86XK_Sleep},
        {Qt::Key_LightBulb, XF86XK_LightBulb},
        {Qt::Key_Shop, XF86XK_Shop},
        {Qt::Key_History, XF86XK_History},
        {Qt::Key_AddFavorite, XF86XK_AddFavorite},
        {Qt::Key_HotLinks, XF86XK_HotLinks},
        {Qt::Key_BrightnessAdjust, XF86XK_BrightnessAdjust},
        {Qt::Key_Finance, XF86XK_Finance},
        {Qt::Key_Community, XF86XK_Community},
        {Qt::Key_AudioRewind, XF86XK_AudioRewind},
        {Qt::Key_BackForward, XF86XK_BackForward},
        {Qt::Key_ApplicationLeft, XF86XK_ApplicationLeft},
        {Qt::Key_ApplicationRight, XF86XK_ApplicationRight},
        {Qt::Key_Book, XF86XK_Book},
        {Qt::Key_CD, XF86XK_CD},
        {Qt::Key_Calculator, XF86XK_Calculater},
        {Qt::Key_Clear, XF86XK_Clear},
        {Qt::Key_ClearGrab, XF86XK_ClearGrab},
        {Qt::Key_Close, XF86XK_Close},
        {Qt::Key_Copy, XF86XK_Copy},
        {Qt::Key_Cut, XF86XK_Cut},
        {Qt::Key_Display, XF86XK_Display},
        {Qt::Key_DOS, XF86XK_DOS},
        {Qt::Key_Documents, XF86XK_Documents},
        {Qt::Key_Excel, XF86XK_Excel},
        {Qt::Key_Explorer, XF86XK_Explorer},
        {Qt::Key_Game, XF86XK_Game},
        {Qt::Key_Go, XF86XK_Go},
        {Qt::Key_iTouch, XF86XK_iTouch},
        {Qt::Key_LogOff, XF86XK_LogOff},
        {Qt::Key_Market, XF86XK_Market},
        {Qt::Key_Meeting, XF86XK_Meeting},
        {Qt::Key_MenuKB, XF86XK_MenuKB},
        {Qt::Key_MenuPB, XF86XK_MenuPB},
        {Qt::Key_MySites, XF86XK_MySites},
        {Qt::Key_New, XF86XK_New},
        {Qt::Key_News, XF86XK_News},
        {Qt::Key_OfficeHome, XF86XK_OfficeHome},
        {Qt::Key_Open, XF86XK_Open},
        {Qt::Key_Option, XF86XK_Option},
        {Qt::Key_Paste, XF86XK_Paste},
        {Qt::Key_Phone, XF86XK_Phone},
        {Qt::Key_Reply, XF86XK_Reply},
        {Qt::Key_Reload, XF86XK_Reload},
        {Qt::Key_RotateWindows, XF86XK_RotateWindows},
        {Qt::Key_RotationPB, XF86XK_RotationPB},
        {Qt::Key_RotationKB, XF86XK_RotationKB},
        {Qt::Key_Save, XF86XK_Save},
        {Qt::Key_Send, XF86XK_Send},
        {Qt::Key_Spell, XF86XK_Spell},
        {Qt::Key_SplitScreen, XF86XK_SplitScreen},
        {Qt::Key_Support, XF86XK_Support},
        {Qt::Key_TaskPane, XF86XK_TaskPane},
        {Qt::Key_Terminal, XF86XK_Terminal},
        {Qt::Key_Tools, XF86XK_Tools},
        {Qt::Key_Travel, XF86XK_Travel},
        {Qt::Key_Video, XF86XK_Video},
        {Qt::Key_Word, XF86XK_Word},
        {Qt::Key_Xfer, XF86XK_Xfer},
        {Qt::Key_ZoomIn, XF86XK_ZoomIn},
        {Qt::Key_ZoomOut, XF86XK_ZoomOut},
        {Qt::Key_Away, XF86XK_Away},
        {Qt::Key_Messenger, XF86XK_Messenger},
        {Qt::Key_WebCam, XF86XK_WebCam},
        {Qt::Key_MailForward, XF86XK_MailForward},
        {Qt::Key_Pictures, XF86XK_Pictures},
        {Qt::Key_Music, XF86XK_Music},
        {Qt::Key_Battery, XF86XK_Battery},
        {Qt::Key_Bluetooth, XF86XK_Bluetooth},
        {Qt::Key_WLAN, XF86XK_WLAN},
        {Qt::Key_UWB, XF86XK_UWB},
        {Qt::Key_AudioForward, XF86XK_AudioForward},
        {Qt::Key_AudioRepeat, XF86XK_AudioRepeat},
        {Qt::Key_AudioRandomPlay, XF86XK_AudioRandomPlay},
        {Qt::Key_Subtitle, XF86XK_Subtitle},
        {Qt::Key_AudioCycleTrack, XF86XK_AudioCycleTrack},
        {Qt::Key_Time, XF86XK_Time},
        {Qt::Key_Select, XF86XK_Select},
        {Qt::Key_View, XF86XK_View},
        {Qt::Key_TopMenu, XF86XK_TopMenu},
        {Qt::Key_Red, XF86XK_Red},
        {Qt::Key_Green, XF86XK_Green},
        {Qt::Key_Yellow, XF86XK_Yellow},
        {Qt::Key_Blue, XF86XK_Blue},
        {Qt::Key_Bluetooth, XF86XK_Bluetooth},
        {Qt::Key_Suspend, XF86XK_Suspend},
        {Qt::Key_Hibernate, XF86XK_Hibernate},
        {Qt::Key_TouchpadToggle, XF86XK_TouchpadToggle},
        {Qt::Key_TouchpadOn, XF86XK_TouchpadOn},
        {Qt::Key_TouchpadOff, XF86XK_TouchpadOff},
        {Qt::Key_MicMute, XF86XK_AudioMicMute},
        {Qt::Key_Launch2, XF86XK_Launch0},
        {Qt::Key_Launch3, XF86XK_Launch1},
        {Qt::Key_Launch4, XF86XK_Launch2},
        {Qt::Key_Launch5, XF86XK_Launch3},
        {Qt::Key_Launch6, XF86XK_Launch4},
        {Qt::Key_Launch7, XF86XK_Launch5},
        {Qt::Key_Launch8, XF86XK_Launch6},
        {Qt::Key_Launch9, XF86XK_Launch7},
        {Qt::Key_LaunchA, XF86XK_Launch8},
        {Qt::Key_LaunchB, XF86XK_Launch9},
        {Qt::Key_LaunchC, XF86XK_LaunchA},
        {Qt::Key_LaunchD, XF86XK_LaunchB},
        {Qt::Key_LaunchE, XF86XK_LaunchC},
        {Qt::Key_LaunchF, XF86XK_LaunchD},
        {Qt::Key_LaunchG, XF86XK_LaunchE},
        {Qt::Key_LaunchH, XF86XK_LaunchF}
    };

    Qt::Key Keys::xkToKey(KeySym xk)
    {
        for (auto i = x11keys.begin(); i != x11keys.end(); ++i)
            if (i.value() == xk)
                return i.key();
        return Qt::Key_No;
    }

    KeySym Keys::keyToXk(Qt::Key key)
    {
        return x11keys[key];
    }

#endif

#ifdef RAT_OS_WINDOWS
    #include "win32keys.h"
static QMap<Qt::Key, int> win32keys = {
    {Qt::Key_Plus, VK_ADD},
    {Qt::Key_Backspace, VK_BACK},
//    {Qt::Key_Break, VK_CANCEL},
    {Qt::Key_Clear, VK_CLEAR},
    {Qt::Key_NumLock, VK_DECIMAL},
    {Qt::Key_Slash, VK_DIVIDE},
    {Qt::Key_Escape, VK_ESCAPE},
    {Qt::Key_Help, VK_ICO_HELP},

    {Qt::Key_0, VK_KEY_0},
    {Qt::Key_1, VK_KEY_1},
    {Qt::Key_2, VK_KEY_2},
    {Qt::Key_3, VK_KEY_3},
    {Qt::Key_4, VK_KEY_4},
    {Qt::Key_5, VK_KEY_5},
    {Qt::Key_6, VK_KEY_6},
    {Qt::Key_7, VK_KEY_7},
    {Qt::Key_8, VK_KEY_8},
    {Qt::Key_0, VK_KEY_9},

    {Qt::Key_A, VK_KEY_A},
    {Qt::Key_B, VK_KEY_B},
    {Qt::Key_C, VK_KEY_C},
    {Qt::Key_D, VK_KEY_D},
    {Qt::Key_E, VK_KEY_E},
    {Qt::Key_F, VK_KEY_F},
    {Qt::Key_G, VK_KEY_G},
    {Qt::Key_H, VK_KEY_H},
    {Qt::Key_I, VK_KEY_I},
    {Qt::Key_J, VK_KEY_J},
    {Qt::Key_K, VK_KEY_K},
    {Qt::Key_L, VK_KEY_L},
    {Qt::Key_M, VK_KEY_M},
    {Qt::Key_N, VK_KEY_N},
    {Qt::Key_O, VK_KEY_O},
    {Qt::Key_P, VK_KEY_P},
    {Qt::Key_Q, VK_KEY_Q},
    {Qt::Key_R, VK_KEY_R},
    {Qt::Key_S, VK_KEY_S},
    {Qt::Key_T, VK_KEY_T},
    {Qt::Key_U, VK_KEY_U},
    {Qt::Key_V, VK_KEY_V},
    {Qt::Key_W, VK_KEY_W},
    {Qt::Key_X, VK_KEY_X},
    {Qt::Key_Y, VK_KEY_Y},
    {Qt::Key_Z, VK_KEY_Z},

    {Qt::Key_multiply, VK_MULTIPLY},
//    {Qt::Key_None, VK_NONAME},

//    {Qt::Key_num0, VK_NUMPAD0},
//    {Qt::Key_Keypad1, VK_NUMPAD1},
//    {Qt::Key_Keypad2, VK_NUMPAD2},
//    {Qt::Key_Keypad3, VK_NUMPAD3},
//    {Qt::Key_Keypad4, VK_NUMPAD4},
//    {Qt::Key_Keypad5, VK_NUMPAD5},
//    {Qt::Key_Keypad6, VK_NUMPAD6},
//    {Qt::Key_Keypad7, VK_NUMPAD7},
//    {Qt::Key_Keypad8, VK_NUMPAD8},
//    {Qt::Key_Keypad9, VK_NUMPAD9},

    {Qt::Key_Colon, VK_OEM_1},
    {Qt::Key_Greater, VK_OEM_102},
    {Qt::Key_Question, VK_OEM_2},
    {Qt::Key_QuoteLeft, VK_OEM_3},
    {Qt::Key_BracketRight, VK_OEM_4},
    {Qt::Key_Backslash, VK_OEM_5},
    {Qt::Key_BracketRight, VK_OEM_6},
    {Qt::Key_QuoteDbl, VK_OEM_7},
//    {Qt::Key_Exclaim, VK_OEM_8},
    {Qt::Key_At, VK_OEM_ATTN},
    {Qt::Key_Clear, VK_OEM_CLEAR},
    {Qt::Key_Comma, VK_OEM_COMMA},
    {Qt::Key_Minus, VK_OEM_MINUS},
    {Qt::Key_Period, VK_OEM_PERIOD},
    {Qt::Key_Plus, VK_OEM_PLUS},
        {Qt::Key_Return, VK_RETURN},
        {Qt::Key_Enter, VK_RETURN},
    {Qt::Key_Space, VK_SPACE},
    {Qt::Key_Minus, VK_SUBTRACT},
    {Qt::Key_Tab, VK_TAB},

//    {Qt::Key_None, VK__none_},
    {Qt::Key_CapsLock, VK_CAPITAL},
    {Qt::Key_Delete, VK_DELETE},
    {Qt::Key_Down, VK_DOWN},
    {Qt::Key_End, VK_END},

    {Qt::Key_F1, VK_F1},
    {Qt::Key_F2, VK_F2},
    {Qt::Key_F3, VK_F3},
    {Qt::Key_F4, VK_F4},
    {Qt::Key_F5, VK_F5},
    {Qt::Key_F6, VK_F6},
    {Qt::Key_F7, VK_F7},
    {Qt::Key_F8, VK_F8},
    {Qt::Key_F9, VK_F9},
    {Qt::Key_F10, VK_F10},
    {Qt::Key_F11, VK_F11},
    {Qt::Key_F12, VK_F12},
    {Qt::Key_F13, VK_F13},
    {Qt::Key_F14, VK_F14},
    {Qt::Key_F15, VK_F15},

    {Qt::Key_Help, VK_HELP},
    {Qt::Key_Home, VK_HOME},
    {Qt::Key_Insert, VK_INSERT},
//    {Qt::Key_LeftControl, VK_LCONTROL},
    {Qt::Key_Left, VK_LEFT},
//    {Qt::Key_LeftAlt, VK_LMENU},
//    {Qt::Key_LeftShift, VK_LSHIFT},
//    {Qt::Key_LeftWindows, VK_LWIN},
    {Qt::Key_PageDown, VK_NEXT},
    {Qt::Key_NumLock, VK_NUMLOCK},
    {Qt::Key_Pause, VK_PAUSE},
    {Qt::Key_Print, VK_PRINT},
    {Qt::Key_PageUp, VK_PRIOR},
//    {Qt::Key_RightControl, VK_RCONTROL},
    {Qt::Key_Right, VK_RIGHT},

//    {Qt::Key_RightAlt, VK_RMENU},
//    {Qt::Key_RightShift, VK_RSHIFT},
//    {Qt::Key_RightWindows, VK_RWIN},
    {Qt::Key_ScrollLock, VK_SCROLL},
    {Qt::Key_SysReq, VK_SNAPSHOT},
    {Qt::Key_Up, VK_UP}
};

Qt::Key Keys::vkToKey(int xk)
{
    for (auto i = win32keys.begin(); i != win32keys.end(); ++i)
        if (i.value() == xk)
            return i.key();
    return Qt::Key_No;
}

int Keys::keyToVk(Qt::Key key)
{
    return win32keys[key];
}
#endif


QByteArray Keys::toString(const Qt::Key &key)
{
    return keys[key];
}
